name: bluetooth_enable
description: Flutter plugin to turn on bluetooth within app
version: 0.1.4
homepage: https://github.com/huitingyeong/bluetooth_enable

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.hui.bluetooth_enable
        pluginClass: BluetoothEnablePlugin
      ios:
        pluginClass: BluetoothEnablePlugin